### PR TITLE
Make node schema maxItemsFrom and molecule aware

### PR DESCRIPTION
**Pull request by sverhoeven**
Refs #59

To test on small catalog
1. Start app
2. select the `molaware` catalog
3. fill the molecules array in the global parameters with some PDB files, downloaded from https://www.rcsb.org
4. Add a node and open its form
5. The properties should have maxItems equal to the number of molecule files that where uploaded.
6. The node 3 and 4 use the PDB files to limit the allowed chains and residues in their props. A PDB file with just chain 'A' should only allow 'A' to be selected in the chain property. A PDB files with residue number 1..100 should only allow 1..100 to be selected in the residue property.

To test on haddock catalog
1. Start app
2. select the `haddock3expert` catalog
3. fill the molecules array in the global parameters with some PDB files, downloaded from https://www.rcsb.org
4. Add `rigidbody` node, edit, expand molecule
   - mol_fix_origin has max items of number of molecules
5. Add `flexref` node, edit, expand flexibility
   - seg has same number of items as molecules
   - seg start/end have residues

To test validation of upload
1. Start app
2. select the `haddock3expert` catalog
3. Upload [workflow (18).zip](https://github.com/i-VRESSE/workflow-builder/files/8553737/workflow.18.zip) which is valid
4. Upload [workflow-bad-resnum.zip](https://github.com/i-VRESSE/workflow-builder/files/8554746/workflow-bad-resnum.zip) which has bad residue number
5. For validation errors see DevTools console

### CODE REVIEW

**Review by Peter9192 — COMMENTED** [review]
For starters, here are my experiences from testing the new functionality. I have not yet looked at (all) the code. Some of these might be for follow up, others you might want to address here. 

It is difficult to know which setting belongs to which molecule. It might be helpful to display the name/filename or other metadata aboutthe molecule in the builder. E.g. 
```
Specifications for molecules:
  Specification for molecule 5t89:
    Is this molecule a shape?
  Specification for molecule 4hhb:
    Is this molecule a shape?
```

The selection of residues in molaware catalog -- node 4 is not very intuitive. It works with ctrl/shift, but it might be nicer to have tick boxes or so.

I am able to build a form with start residue number > end residue number. Shouldn't this be invalid?

Occasionally, the text box doesn't render properly (e.g. `[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]`. Toggling visual/text usually solves the issue.

In haddock expert - under rigidbody, got error message that `['ab initio mode'].rair[0] should be array`. Initially an empty table is shown, adding an empty row fixes it.

The flexref example has a couple of issues:
- You need to add (empty) rows to the tables for `seg` and `fle`, otherwise the `submit` button doesn't work. However, the error message appears at the top, far above my scroll position.
- If I start with one molecule, add flexref settings, then go back and add another molecule, there is no extra array item for seg/fle so I cannot modify settings for the second molecule.
- If I remove a molecule, and try to modify flexref for the remaining one, I get `.flexibility.seg should NOT have more than 1 items`, but I cannot remove old items because the second table is no longer rendered.

Upload validation: I get validation errors for both files. Happens in Chrome and Firefox. I expected the valid workflow to succeed. The error messages are very unclear, so something else than the residue number seems to be going wrong.

**Comment by sverhoeven** [comment]
> For starters, here are my experiences from testing the new functionality. Some of these might be for follow up, others you might want to address here. I have not yet looked at (all) the code, so will follow up with that.
>

Thanks for testing out the user interface.

> It is difficult to know which setting belongs to which molecule. It might be helpful to display the name/filename or other metadata aboutthe molecule in the builder. E.g.
>
> ```
> Specifications for molecules:
>   Specification for molecule 5t89:
>     Is this molecule a shape?
>   Specification for molecule 4hhb:
>     Is this molecule a shape?
> ```

Can be solved later, created https://github.com/i-VRESSE/workflow-builder/issues/57

>
> The selection of residues in molaware catalog -- node 4 is not very intuitive. It works with ctrl/shift, but it might be nicer to have tick boxes or so.
>

Can be solved later, created https://github.com/i-VRESSE/workflow-builder/issues/72

> I am able to build a form with start residue number > end residue number. Shouldn't this be invalid?

At the moment there is no way to specifiy that validation rule. We have a lot of other advanced validation we want to work on later, so for now I created https://github.com/i-VRESSE/workflow-builder/issues/73

>
> Occasionally, the text box doesn't render properly (e.g. `[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]`. Toggling visual/text usually solves the issue.
>

I have seen this before, but have not been able to find a way to reproduce it. Created https://github.com/i-VRESSE/workflow-builder/issues/74

Replies on the rest of your review will follow later.

**Comment by sverhoeven** [comment]
...

> 
> In haddock expert - under rigidbody, got error message that `['ab initio mode'].rair[0] should be array`. Initially an empty table is shown, adding an empty row fixes it.

Added workaround to set default to an array.

> 
> The flexref example has a couple of issues:
> 
> * You need to add (empty) rows to the tables for `seg` and `fle`, otherwise the `submit` button doesn't work. However, the error message appears at the top, far above my scroll position.

Added workaround to set default to an array.

> * If I start with one molecule, add flexref settings, then go back and add another molecule, there is no extra array item for seg/fle so I cannot modify settings for the second molecule.

You are a thorough tester, that is a usecase I did not think about. 
I have added integration test for it, so I can replicate the error, but have not yet fixed it.

> * If I remove a molecule, and try to modify flexref for the remaining one, I get `.flexibility.seg should NOT have more than 1 items`, but I cannot remove old items because the second table is no longer rendered.

You are a very thorough tester, that is a usecase I did not think about.
Will fix after other integration test

> 
> Upload validation: I get validation errors for both files. Happens in Chrome and Firefox. I expected the valid workflow to succeed. The error messages are very unclear, so something else than the residue number seems to be going wrong.

Started https://github.com/i-VRESSE/workflow-builder/pull/75 for clearer error message.

**Comment by sverhoeven** [comment]
Spawned https://github.com/i-VRESSE/workflow-builder/issues/78 . 

So all review remarks have been fixed or spawned into new issues/PRs.
Merging this PR to prevent branch of branch PRs.

**Pull request merged**
